coreos/cap-std-ext

src/lib.rs

This exports our specific version of `rustix`. It is part of our
public API, e.g. through `OwnedFd` usage.

lib: export rustix too

---

src/tempfile.rs

Sadly RHEL8's `overlayfs` doesn't support it, and we end up using
that in many places obviously.
The more I think about this the more I think we should try to
land this code in `cap-tempfile`.

tempfile: Add support for no-`O_TMPFILE`

---

src/cmdext.rs
tests/it/main.rs

This is a very natural extension to capability APIs.  In rpm-ostree
we want to invoke `cpio` in a specified directory.
I originally had this just take an `Arc<Dir>` but needed to add
dynamic dispatch so we can use a tempdir.

cmdext: Add `cwd_dir()` API

---

src/dirext.rs
tests/it/main.rs

A trap I've been hitting when porting our helpers from `openat`
to `cap-std` is around symlink following.
It actually makes sense that our `metadata_optional()` wrapper
does follow symlinks, just like `metadata()`.  But, there are a ton
of paths where we don't want to follow symlinks, so add that
wrapper too.

Add `symlink_metadata_optional()`

---

Cargo.toml
src/cmdext.rs
tests/it/main.rs

On general principle, but specifically this will help get
rpm-ostree out of having two rustix versions
because `memfd` pulls in rustix 0.35 already.

Bump to cap-std 0.25 and rustix 0.35

---

.github/workflows/rust.yml
Cargo.toml

ci: Bump MSRV
This matches other CoreOS projects, and lets us use Edition 2021.
---
Update to Rust 2021
No major changes.
```
$ cargo fix --edition
note: Switching to Edition 2021 will enable the use of the version 2 feature resolver in Cargo.
This may cause some dependencies to be built with fewer features enabled than previously.
More information about the resolver changes may be found at https://doc.rust-lang.org/nightly/edition-guide/rust-2021/default-cargo-resolver.html
When building the following dependencies, the given features will no longer be used:
getrandom v0.2.7 removed features: std
libc v0.2.126 removed features: default, extra_traits, std
```
---

Update to Rust 2021

---

src/cmdext.rs
tests/it/main.rs

As the docstring says it only really works on `TempDir` which
isn't very useful.  I only kept it for compat at the time, but
we bumped semver recently.

cmdext: Remove not-very-usable `cwd_dir_owned`

---

Cargo.toml
src/cmdext.rs
src/dirext.rs
src/lib.rs
tests/it/main.rs

This means we only have to have one crate dependency, not two.
The cost is more import juggling, but that's OK.

Use re-exported `cap_tempfile::cap_std`

---

Cargo.toml

Cargo.toml: Fix repository link
---
Release 0.26.2
To get out the new API.
---

Release 0.26.2

---

Cargo.toml
src/dirext.rs
tests/it/main.rs

This mirrors https://github.com/coreos/openat-ext/pull/36/commits/1df874d328d507d6bb2b41a1fcfecf002602677d
And for the same reason - we're going to use it in the rpm-ostree port
to cap-std.

dirext: Add an `update_timestamps()` API

---

Cargo.toml
src/cmdext.rs
tests/it/main.rs

This will end one major source of semver bumps for our reverse dependencies.
For our API...it's not perfect, but it's working well enough and I think we can commit to it.

Bump to 1.0, matching cap-std

---

src/lib.rs

For the same reason we re-export cap-std; this way our consumers only have one thing they need in `Cargo.toml` that can be bumped atomically.

lib: Also re-export cap-tempfile

---

Cargo.toml
src/cmdext.rs

Just on general principle, no reason to add our own requirements here.

Use re-exported `io_lifetimes`

---

.github/workflows/rust.yml

This updates to match https://github.com/containers/containers-image-proxy-rs/pull/40
- Use `checkout@v3` to avoid deprecation warnings
- switch to https://github.com/dtolnay/rust-toolchain after seeing https://www.reddit.com/r/rust/comments/z1mlls/actionsrs_github_actions_need_more_maintainers_or/
We also now also for now don't use the fcos buildroot, because we don't need to.

ci: Revamp

---

src/dirext.rs

It looks like probably
https://github.com/bytecodealliance/rustix/commit/69af396b79e296717bece8148b1f6165b810885c broke our build on 32 bit because we were implicitly relying on `struct TimeSpec` being `Copy`, but it lost that only on 32 bit.
Use `.clone()`.

dirext: Fix build on 32 bit

---

Cargo.toml

It looks like a backported change in the 0.36 series started requiring this.

build: Add `process` feature for rustix

---

Cargo.toml
src/lib.rs

lib: Bump to semver 2.0
Prep for breaking changes.
---
lib: Drop re-export of rustix
In hindsight this was a bad idea because we need to bump
our semver whenever rustix does.
---

Drop rustix export

---

Cargo.toml
README.md
src/lib.rs

lib: Re-export cap-primitives
For the same reason we re-export `cap-std`; in practice it needs
to be version locked.
(I know the idea of `cap-primitives` is that it's an implementation
detail, but in practice cap-std also re-exports at least `ipnet`
from it, so...it kind of has to be equally stable)
---
README.md: Add crates.io and docs.rs links
They're handy.
---

lib: Re-export cap-primitives

---

Cargo.toml

This just has the cap-primitives reexport.

Release 3.0.1

---

Cargo.toml
src/dirext.rs
tests/it/main.rs

Adapt to the changes in that crate, xref
https://github.com/bytecodealliance/cap-std/pull/343

Update to cap-std 3, bump to 4

---

.github/workflows/rust.yml
Cargo.toml
src/dirext.rs
src/lib.rs
tests/it/main.rs

I'd like to potentially start making use of the `fs_utf8::Dir` in a lot of code in e.g. bootc/ostree related things because ostree in particular hard requires UTF-8 filenames, and we have redundant verifications.
This makes use of the new `as_cap_std()` API that landed in cap-std.

Add a fs_utf8 feature

---

Cargo.toml
src/dirext.rs
tests/it/main.rs

More convenience helpers, particularly for the use case where one wants to gather a list of filenames (possibly filtered) and sort them.
(We don't do sorting here, but it's trivial to do after calling
`filenames_filtered()`)

dir+utf8: Add `filenames` and `filenames_filtered`

---

Cargo.toml
src/dirext.rs
tests/it/main.rs

Copy the code from https://github.com/ostreedev/ostree-rs-ext/pull/551 as it's better here.

dir: Add an `is_mountpoint` API

---

src/cmdext.rs

I *did* test the tests, but then in trying to unify them I messed up the range syntax, so we effectively lost the test.
Just noticed this when going to do a release and glancing at the code...

tests: Fix range

---

src/dirext.rs
tests/it/main.rs

Imported from bootc
https://github.com/containers/bootc/blob/0fc7830916f43e95aeffda73810d2a10a2980e8a/lib/src/utils.rs#L114
This is generally useful.

dirext: Add open_dir_noxdev

---

Cargo.toml
src/dirext.rs
tests/it/main.rs

There's a ton of use cases for a recursive directory walk, and we end up re-implementing it over and over.
Unlike the `walkdir` crate, this runs via "internal iteration" that accepts a closure which returns `std::ops::ControlFlow` to ensure the caller can break out of iteration.
There's a config option that supports:
- Not traversing mount points
- Sorting entries

Add a `walk` method

---

src/lib.rs

I think this got cargo culted from elsewhere; where necessary I believe the status quo is to use `#![cfg(docsrs)]` or so.
This squashes a build warning.

lib: Drop unused feature

---

src/dirext.rs
src/lib.rs
src/xattrs.rs
tests/it/main.rs

There's a lot of subtleties to these APIs. First,
unlike the `xattrs` crate, we operate on cap-std `Dir` objects. As part of that, we also explicitly error out on absolute paths, as well as paths containing any uplinks (`../`) at all.
- Always use `/proc/self/fd` with `lgetxattr` because this is the only way to get/set xattrs on symlinks.
- Return a `Result<Option<>>` with getxattr for consistency with our other APIs to handle the common case of looking for a nonexistent xattr.
- The `getxattr` API is also higher level than what Rustix offers to be maximally convenient; we always return an owned buffer, and handle resizing it.

dirext: Add getxattr/setxattr wrappers

---

src/dirext.rs
tests/it/main.rs

This came up in a bootc PR that would have been cleaner with this.

dirext: Add APIs to read whole contents optionally

---

src/cmdext.rs
tests/it/main.rs

We have this in bootc, but it's generally useful.

cmdext: Add prctl wrapper
